spring:
  cloud:
    stream:
      default-binder: kafka
      function:
        bindings:
          upper-in-0: input
          upper-out-0: output

management:
  endpoints:
    web:
      exposure:
        include: info, health, shutdown, prometheus