spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: never
  batch:
    jdbc:
      initialize-schema: always
  application:
    name: fileingest


logging:
  level:
    org.springframework.cloud.task: DEBUG