spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scdf
    username: root
    password: dataflow
    driverClassName: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: never
  application:
    name: fileingest
  batch:
    jdbc:
      initialize-schema: never

logging:
  level:
    org.springframework.cloud.task: DEBUG